using Unity.Mathematics;
using UnityEngine;

public class CameraController : MonoBehaviour
{
    public float sensitivyX;
    public float sensitivyY;
    public Transform orientation;
    private float mouseX;
    private float mouseY;

    private float xRotation;
    private float yRotation;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        Cursor.lockState = CursorLockMode.Locked;
        Cursor.visible = false;
    }

    // Update is called once per frame
    void Update()
    {
        MouseControl();
    }

    void MouseControl()
    {
        mouseX = Input.GetAxisRaw("Mouse X") * Time.deltaTime * sensitivyX;
        mouseY = Input.GetAxisRaw("Mouse Y") * Time.deltaTime * sensitivyY;

        yRotation += mouseX;
        xRotation -= mouseY;

        xRotation = Mathf.Clamp(xRotation, -90f, 90f);

        transform.rotation = Quaternion.Euler(xRotation, yRotation, 0);
        orientation.rotation = Quaternion.Euler(0, yRotation, 0);
    }
}
